<?php declare(strict_types=1); ?><!doctype html>
<html lang="hu"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RaktárPont</title><link rel="stylesheet" href="style.css"></head>
<body>
<header><a class="brand" href="index.php"><span>RP</span> RaktárPont</a><?php if(user()): ?><div class="profile"><b><?=e(user()['username'])?></b><small><?=e(role_labels()[user()['role']])?></small><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><button class="link" name="action" value="logout">Kilépés</button></form></div><?php endif?></header>
<main>
<?php if($flash): ?><div class="flash <?=e($flash[1])?>"><?=e($flash[0])?></div><?php endif?>
<?php if($userCount===0): ?>
<section class="auth"><p class="eyebrow">ELSŐ INDÍTÁS</p><h1>Admin fiók létrehozása</h1><p>Hozd létre a rendszer első, teljes jogosultságú kezelőjét.</p><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><label>Felhasználónév<input name="username" required maxlength="50" autocomplete="username"></label><label>Jelszó<input type="password" name="password" required minlength="10" autocomplete="new-password"></label><button name="action" value="setup">Admin létrehozása</button></form></section>
<?php elseif(!user()): ?>
<section class="auth"><p class="eyebrow">ÜDV ÚJRA</p><h1>Belépés a raktárba</h1><p>Készletkezelés egyszerűen, egy helyen.</p><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><label>Felhasználónév<input name="username" required autofocus autocomplete="username"></label><label>Jelszó<input type="password" name="password" required autocomplete="current-password"></label><button name="action" value="login">Belépés</button></form></section>
<?php else: ?>
<div class="hero"><div><p class="eyebrow">ÁTTEKINTÉS</p><h1>Készletkezelés</h1><p><?=count($inventories)?> elérhető raktár · <?=count($items)?> tétel a kiválasztott raktárban</p></div><?php if(is_admin()): ?><details><summary>+ Új raktár</summary><form method="post" class="popover"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input name="name" placeholder="Raktár neve" required><input name="location" placeholder="Helyszín"><button name="action" value="create_inventory">Létrehozás</button></form></details><?php endif?></div>
<nav class="tabs"><?php foreach($inventories as $inv): ?><a class="<?=$selected===(int)$inv['id']?'active':''?>" href="?inventory=<?=$inv['id']?>"><?=e($inv['name'])?><small><?=e($inv['location'])?></small></a><?php endforeach?></nav>
<?php if(!$inventories): ?><section class="empty"><h2>Még nincs elérhető raktár</h2><p><?=is_admin()?'Hozd létre az első raktárat a fenti gombbal.':'Kérj hozzáférést egy supervisortól.'?></p></section><?php else: ?>
<?php if(can_write()): ?><details class="panel add"><summary>+ Készlettétel felvétele vagy frissítése</summary><form method="post" class="grid-form"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="inventory_id" value="<?=$selected?>"><label>Cikkszám<input name="sku" required maxlength="60"></label><label>Megnevezés<input name="name" required></label><label>Mennyiség<input name="quantity" type="number" min="0" required></label><label>Egység<input name="unit" value="db" required maxlength="20"></label><label class="wide">Megjegyzés<input name="note" maxlength="500"></label><button name="action" value="save_item">Mentés</button></form></details><?php endif?>
<section class="panel"><div class="panel-title"><h2>Készlet</h2><span><?=count($items)?> tétel</span></div><div class="table-wrap"><table><thead><tr><th>Cikkszám</th><th>Megnevezés</th><th>Mennyiség</th><th>Megjegyzés</th><th>Frissítve</th><?php if(is_admin()):?><th></th><?php endif?></tr></thead><tbody><?php foreach($items as $item): ?><tr><td><code><?=e($item['sku'])?></code></td><td><b><?=e($item['name'])?></b></td><td><strong><?=e($item['quantity'])?></strong> <?=e($item['unit'])?></td><td><?=e($item['note']?:'—')?></td><td><?=e($item['updated_at'])?><small><?=e($item['username']??'törölt felhasználó')?></small></td><?php if(is_admin()):?><td><form method="post" onsubmit="return confirm('Biztosan törlöd?')"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="inventory_id" value="<?=$selected?>"><input type="hidden" name="item_id" value="<?=$item['id']?>"><button class="danger-link" name="action" value="delete_item">Törlés</button></form></td><?php endif?></tr><?php endforeach?><?php if(!$items):?><tr><td colspan="6" class="muted">Ebben a raktárban még nincs készlettétel.</td></tr><?php endif?></tbody></table></div></section>
<?php if(is_supervisor()): ?><section class="panel"><div class="panel-title"><div><p class="eyebrow">JOGOSULTSÁGOK</p><h2>Csapat és hozzáférések</h2></div></div><form method="post" class="grid-form user-form"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><label>Új felhasználó<input name="username" required></label><label>Ideiglenes jelszó<input type="password" name="password" minlength="10" required></label><label>Szerepkör<select name="role"><?php foreach(role_labels() as $value=>$label): if(!is_admin()&&$value>1)continue;?><option value="<?=$value?>"><?=e($label)?> (<?=$value?>)</option><?php endforeach?></select></label><button name="action" value="create_user">Felvétel</button></form><div class="access-list"><?php foreach($users as $u):?><div><span class="avatar"><?=e(mb_strtoupper(mb_substr($u['username'],0,1)))?></span><span><b><?=e($u['username'])?></b><small><?=e(role_labels()[$u['role']])?></small></span><?php if($u['role']!==ROLE_ADMIN && $u['id']!==user()['id']):?><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="user_id" value="<?=$u['id']?>"><input type="hidden" name="inventory_id" value="<?=$selected?>"><label class="switch"><input type="checkbox" name="allowed" onchange="this.form.submit()" <?=isset($access[(int)$u['id']][$selected])?'checked':''?>><span></span> Hozzáfér</label><input type="hidden" name="action" value="save_access"></form><?php else:?><em>Teljes hozzáférés</em><?php endif?></div><?php endforeach?></div></section><?php endif?>
<?php if(is_admin()):?><form method="post" class="delete-warehouse" onsubmit="return confirm('A raktár és minden tétele végleg törlődik. Folytatod?')"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="inventory_id" value="<?=$selected?>"><button class="danger" name="action" value="delete_inventory">Raktár végleges törlése</button></form><?php endif?>
<?php endif; endif; ?>
</main><footer>RaktárPont · SQLite alapú belső készletkezelő</footer></body></html>
